# video name.it is should be like: xx/xxx_w*h_xxfps.yuv
input: '/media/ryan/D/testVideo/RaceNight_1920x1080_50fps_8bit.yuv'
# input: '/media/ryan/D/Datasets/HEVC/BasketballDrill_832x480_50fps.yuv'
outputFolder: 'results/'
# 视频降帧参数
# downFrameRateStage:
#   BinaryFileProcess:
#     downRate: [1]

# 视频绛分辨率参数
# downResolutionStage: 
#   FFmpeg:
#     downRate: [1]

encodingStage:
  HEVC:
    crf: [20,25,32,40]
    codec: 'hevc_nvenc' #'libx265'
    keyint: 50
    # preset: 'medium'
    # tune: 'zerolatency'
    g: 50
    # level: 3.1
    vframes: 50
    bppRef: 'input' #'predecessor'

  # VVC:
  #   crf: [20,25,32,40]
  #   mode: 'lowdelay_P'
  #   frames: 50
  #   level: 3.1

  #  HLVC:
  #    lumda: [256,512,1024,2048]

# In analyzerStage, we recommend that you do not use both methods at once.
# Because different methods will produce different graphics paths.
# But in fact, considering that the analyzerStage only makes
# the soft symbolic to link to the input file, the latter stage
# will actually process the same input file.
analyzerStage0:
  PSNR:
    useDataType: 'YUV'

# upResolutionStage:
#   USR: 'NoParams'

# we use pyyaml that does not allow to use same key in the same file
# to load this config file.To solve this problem, we add a number after
# stage name.
# analyzerStage1:
#   PSNR:
#     useDataType: 'YUV'

# upFrameRateStage:
#   DAIN: 'NoParams'

# analyzerStage2:
#   PSNR:
#     useDataType: 'YUV'
  # FID: 'NoParams'
  # NIQE: 'NoParams'

visualizationResultStage:
  Flow: 'NoParams'
  # This mathod always gets the last PSNR value
  BppMetrics: 'NoParams'
