# video name.it is should be like: xx/xxx_w*h_xxfps.yuv
input: '/media/ryan/D/testVideo/FlowerKids_640x448_50fps.yuv'
outputFolder: 'results/'
# 视频降帧参数
downFrameRateStage:
  BinaryFileProcess:
    downRate: [1,]

# 视频绛分辨率参数
downResolutionStage: 
  FFmpeg:
    downRate: [1,]

encodingStage:
  HEVC:
    Q: [20,30,40,50]
    keyInterval: 10
    bppRef: 'input' # 'predecessor'
  #  VVC:
  #    Q: [20, 25, 30, 35, 40, 45]
  #  HLVC:
  #    lumda: [256,512,1024,2048]
analyzerStage0:
  PSNR:
    useDataType: 'YUV'

upResolutionStage:
  USR: 'NoParams'

analyzerStage1:
  PSNR:
    useDataType: 'YUV'

upFrameRateStage:
  DAIN: 'NoParams'

analyzerStage2:
  PSNR:
    useDataType: 'YUV'

visualizationResultStage:
  Flow: 'NoParams'
  # This mathod always gets the last PSNR value
  BppPSNR: 'NoParams'
