# video name.it is should be like: xx/xxx_w*h_xxfps.yuv
input: '/media/ryan/D/testVideo/11221_1920x1080_25fps_8bit.yuv'
# input: '/media/ryan/D/Datasets/cannotcompression/1_1920x1080_25fps.yuv'
outputFolder: 'results/'

encodingStage:
  HEVC_NVENC:
    cq: [14,20,26,32,40,43,46,49,51]
    # qmin: [10,20,30,40,50,60,69]
    # qmax: [10,200,400,600,800,1000]
    keyint_min: 50
    g: 50
    vframes: 500
    bppRef: 'input'

# In analyzerStage, we recommend that you do not use both methods at once.
# Because different methods will produce different graphics paths.
# But in fact, considering that the analyzerStage only makes
# the soft symbolic to link to the input file, the latter stage
# will actually process the same input file.
analyzerStage0:
  PSNR:
    useDataType: 'YUV'

visualizationResultStage:
  Flow: 'NoParams'
  # This mathod always gets the last PSNR value
  BppMetrics: 'NoParams'
